### ISSUE TITLE
Dependencies in readme

### ISSUE THREAD

**Issue by RaccoonMusicPlayer** [ChrisOh431/ELPath#3]
Hey,

You seem to have updated ELPATH to be compatible with Dear PyGui 1.x, but the [dependencies listed](https://github.com/ChrisOh431/ELPath#dependencies) on your readme state DearPyGui v0.8.62.

I'm assuming it runs well on DPG 1.x and you can update the readme.

**Comment by ChrisOh431** [comment]
updated the dependencies, thanks!
