### ISSUE TITLE
Nonetype

### ISSUE THREAD

**Issue by bandit-masked** [ChrisOh431/ELPath#4]
Running ELPath results in the following error. `ImportError: cannot import name 'NoneType' from 'types'`. NoneType seems to be deprecated in recent Python versions. Are you using an older version of Python?

**Comment by ChrisOh431** [comment]
What version of python are you running?

**Comment by ChrisOh431** [comment]
I missed the memo that NoneType is deprecated and was using it for a comparison. It should be fixed now, thanks for the issue!

**Comment by bandit-masked** [comment]
I got it working on my computer now. 

There was one curious error cause by the following code on line 48 in ELPath.py.
```Python
dpg.bind_font(dpg.add_font("resources/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf", 20))
```
If I replace it with the following line by add `../` in there, it works.

```Python
dpg.bind_font(dpg.add_font("../resources/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf", 20))
```
The peculiar thing here is that someone else had the same problem with an app I made. I have no idea whether this is an issue with DPG, Python or Windows.

**Comment by bandit-masked** [comment]
I think the app would do well on reddit.com/r/python or other programming sub-reddits. Mind if I post there?

**Comment by ChrisOh431** [comment]
> I got it working on my computer now.
> 
> There was one curious error cause by the following code on line 48 in ELPath.py.
> 
> ```python
> dpg.bind_font(dpg.add_font("resources/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf", 20))
> ```
> 
> If I replace it with the following line by add `../` in there, it works.
> 
> ```python
> dpg.bind_font(dpg.add_font("../resources/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf", 20))
> ```
> 
> The peculiar thing here is that someone else had the same problem with an app I made. I have no idea whether this is an issue with DPG, Python or Windows.

I'm pondering the best solution to this part, either I'm moving the resources directory or using `os` for paths.

**Comment by ChrisOh431** [comment]
> I think the app would do well on reddit.com/r/python or other programming sub-reddits. Mind if I post there?

Go ahead, I'd be honored!

**Comment by bandit-masked** [comment]
I'll let you know when I have.

**Comment by bandit-masked** [comment]
I checked with the DPG core devs. It's probably a different between Linux and Windows... Pathlib was recommended. I haven't tried myself yet.

**Comment by ChrisOh431** [comment]
Moved the resources folder, font should load fine now. Thanks!

**Comment by bandit-masked** [comment]
Can confirm, font problem solved!

Why do you apply a 1.2 font scale factor? The font would be clearer if you just load it as 28 pixels.

**Comment by ChrisOh431** [comment]
Didn't realize that scaling would affect aliasing. Thanks for pointing that out, I've modified the load.

**Comment by bandit-masked** [comment]
You are welcome. For optimal font sharpness in DPG, you should always load at the appropriate size. If you are using different sizes, you should load the font at each size.

El Path is a cool app, so I'd like it to look its best. Developers on Reddit generally likes sorting apps  ¯\_(ツ)_/¯
